[[redirects]]
  from = "https://www.baiesound.com/*"
  to = "https://baiesound.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://baiesound.com/*"
  to = "https://baiesound.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://timely-khapse-59566e.netlify.app/*"
  to = "https://baiesound.com/:splat"
  status = 301
  force = true
